define k = Character(_("KARKAT"), color="#dddddd", what_color="#dddddd")
define g = Character(_("GAMZEE"), color="#880088", what_color="#bb00bb")
define d = Character(_("DAVE"), color="#ee0000", what_color="#ee0000")
define j = Character(_("JOHN"), color="#0000ee", what_color="#0000ee")

label start:
    "You've never had a dream this amazing before. Gold shines from every one of the myriad towers, and the clouds above you morph into fantastical shapes. You fly above the streets, zipping through the air and teleporting about in your warm, golden pajamas. It's pure bliss."
    "Far below you, little white chess people mull around. You drift around the glittering city until you see a massive tower. It towers (what else are towers supposed to do?) above everything else. Clearly, this is a place of importance."
    "You float in to find a boy with nubby horns and pajamas like yours lying curled up in his dream bed, sleeping soundly."
    "He looks so peaceful. You imagine this is a very peaceful alien boy."
    "Abruptly, the boy vanishes. Oh shoot!"
    scene bg room with fade
    "\[zap.\]"
    "You've vanished too!"
    "When your vision adjusts, you find yourself in a dim, alien room. There's a bookshelf and a desk and clothes hung up on pegs on the wall. But instead of a bed there is a small tub of green goo. Hmm."
    k "WHAT"
    k "THE HECK!"
    play music "Project1.mp3"
    "A gravelly voice tinged with mania crashes over you in a furious wave. You reel back from the onslaught."
    k "EVERY EVENING I WAKE UP TO ANOTHER GLORIOUS NIGHT OF THE UNIVERSE APPLYING ITS INGLORIOUS SENSE OF HUMOR DIRECTLY TO MY FACE IN THE MOST HUMILLIATING AND JUVENILE WAY POSSIBLE."
    k "I'M USED TO THIS, OKAY? I'M NOT SAYING THIS IS ANYTHING NEW."
    k "BUT THIS IS JUST NEXT FREAKING LEVEL."
    "Your eyes finally adjust enough to see the same alien boy from the dream world. He appears to have fallen asleep at his computer: some crumbs are stuck to his face where it had been pressed to the desk. He's got a zodiac symbol on his shirt. Perhaps forewarningly, cancer."
    "And man, he is angry. Like, way angrier than a normal person."
    k "I STAY IN THIS CRUMBLING EXCUSE OF A HIVE, RIG THIS PLACE WITH EARLY WARNING SYSTEMS, AND WHAT'S MY REWARD?"
    k "AN ALIEN TELEPORTING INTO MY RESPITEBLOCK LIKE A FREAKING—"
    hide k
    "Zap! Suddenly, you're outside and away from the infuriated grey man. You still have teleportation powers like in your dream, but something tells you you aren't still sleeping."
    "Well, zapping powers are cool. And probably really useful because dang, you don't know what kind of early warning system he has, but whatever predators it's meant to keep away, all he'd have to do is shout at them."
    "You look around. You're on a nearby hill about a hundred yards away from the boy's hive. From the outside it's large and leaning with square windows and an unnecessary number of balconies, although who are you to say what's necessary? Maybe this dude really likes balconies. He could probably use the fresh air."
    "A couple of similarly large and lopsided hives scatter the skyline. Hmm. Hives. You aren't sure what made you think of calling them that, but it feels right. Maybe because of the organic, insectile architecture, like they were grown instead of built."
    "You clearly aren't on Earth anymore. The sky is black and the bushes are purple, and there are two moons. Neither of them is your grey moon, though."
    "You think maybe you should be freaked out by this strange alien land, but it's just too surreal to fully believe. Besides, you kind of like it here. It's comfortable. This is a pretty good hill."
    "You sit for a while, thinking about this hill and this universe and your place in it, until the sun starts to crest over the distant horizon."
    k "HEY. IDIOT."
    "The troll boy is leaning out of his front door."
    k "YOU'RE SITTING ON THE GROUND WAITING FOR SUNRISE. SO YOU'RE EITHER A JADEBLOOD OR A MORON."
    k "AND I KNOW THE ONLY JADEBLOOD WHO LIVES OUTSIDE THE CAVERNS AND SHE'S A LOT BETTER LOOKING THAN YOU."
    k "SO WHAT THE HELL. WHO ARE YOU. YOU'RE NOT A TROLL."
    "There's a substantial gap of grassy hill between the two of you, but you can hear him just fine. He has a talent for projection. You stand up and brush the dirt off yourself. He seems a bit less angry now."
    "He's gesturing for you to come on, so you walk down the hill. The heat from the rising sun washes over your back, and you speed up. That sun is bad news, you just know it."
    "Light bleeds further across the horizon, and your pace gets a little leisurely."
    "The troll boy crosses his arms. His shoulders are rounded in a slouch, like he spends a lot of time making himself smaller. His black claws are bitten down. You wave an awkward hello."
    "He rolls his eyes and grabs you by the arm, his grip surprisingly strong. He tugs you underneath the shadowed overhang of a balcony."
    k "OKAY, IDIOT. WHAT WERE YOU DOING WATCHING ME IN MY DREAM LIKE SOME HORNLESS WACKO?"
    k "I CAN'T EVEN RETREAT INTO UNCONSCIOUSNESS ANYMORE, IS THAT IT? I WON'T EVEN SLIDE INTO THE NASCENT RELIEF OF DEATH WITHOUT AN ALIEN STALKING ME."
    k "DID ONE OF MY \"FRIENDS\" PUT YOU UP TO THIS?"
    k "WAS IT SOLLUX?"
    k "EVERYBODY'S FAVORITE PASTIME--MAKE KARKAT'S LIFE EVEN MORE OF A CONSTANT, EFFERVESCENT GARBAGELAND."
    "You tell him--Karkat--that it's not like that. You don't know anybody named Sollux, and you didn't mean to be creepy. You just saw him sleeping and suddenly you were in his home. Karkat's thick eyebrows creep upward."
    "Okay, you know how that sounds. But you're confused, too! Especially with the alien planet, dream hopping, and new zappy teleportation powers you've inexplicably gained."
    k "\"ZAPPY\" POWERS? WOW, VERY NORMAL."
    "Well, today's not really a day for normal, is it? But hey, now that you've thought of it, maybe those happy powers are the key to getting back home! What if you teleported there?"
    "Home is rather far away, though. You don't fancy being lost in the middle of space. A little practice might be called for first."
    k "ARE YOU LOOKING AT ME? YOU SHOW UP UNINVITED IN MY HOUSE, AND NOW YOU'RE ASKING FOR HELP?!"
    k "..."
    k "FINE. IF IT GETS YOU OUT OF MY HORNS, DO IT."
    "All right, awesome! You can teleport around here! You can bring him to visit one of his friends! That'll be a way to make up for breaking into his hive. You could visit...Sollux, was it?"
    "Karkat makes a noise like a tea kettle being punched."
    k "HECK NO."
    k "THAT NOOKBITER WOULD SELF-IMMOLATE IF I INTERRUPTED HIS \"CODING\"."
    k "I DON'T HAVE THE ENERGY TO GRUBSIT THAT FREAKY BUZZBALL TODAY."
    "Okay, then where does he want to go? Does he have any more \"friends\"?"
    k "..."
    k "I WOULDN'T CALL HIM A FRIEND EXACTLY."
    k "MORE LIKE AN ENDLESS BURDEN I'VE BEEN CURSED WITH BY THE SLITHERING, ELDRITCH GODS OF THE OUTER REACHES."
    k "IF I DIDN'T OCCASIONALLY CHECK UP ON HIM HE'D SPACE OUT SO FAR HE'D HIT THE VACUUM."
    k "HOW DO WE ZAP THERE?"
    "Hmm. You're actually not quite sure. But you don't want to backpedal and suggest to your host who's barely tolerating your presence that you don't know what you're doing."
    k "DO I JUST..."
    "His hand kind of hovers near yours."
    k "HOLD ON?"
    "You could hold hands, but you don't want to be too awkward. You could also just hold him under the armpits."
    k "YOU THINK HOLDING ME UNDER THE ARMPITS IS LESS WEIRD THAN HOLDING FROND STUMPS?"
    "Uh...yeah. Sort of?"
    "Karkat puts an awkward hand on your elbow. Then he frowns, and pushes up your sleeve, laying three fingers against your bare arm. You good, dude?"
    k "UH. YEAH. SORRY. YOU'RE JUST KIND OF WARM."
    "Thank you! You tell Karkat that he is very warm too."
    k "LET'S JUST GET THIS OVER WITH."
    k "TRY TO AIM FOR JUST OUTSIDE HIS HIVE. HIS LUSUS ISN'T AROUND, AND HE'S USUALLY TOO STONED TO EVEN NOTICE IF THE ROOF CAME DOWN."
    k "BUT I DON'T WANT TO STARTLE HIM."
    "Cool. Here goes!"
    scene bg black with fade
    "\[zap.\]"
    "You zap somewhere pitch black, and immediately blunder right into Karkat."
    k "OH MY GOSH."
    k "COULD YOU KEEP IT TOGETHER FOR A SINGLE FREAKING MOMENT?"
    "You aren't in Karkat's hive anymore. You appear to be in the void! Darn."
    k "THE WHAT?"
    k "LET GO OF ME."
    "You tell Karkat that he is actually the one still holding on to you. He makes an angry noise through his nostrils and releases you from his clammy grasp. He moves away from you, and collides with what sounds like about 17 mops all banging into each other and clattering to the ground."
    k "OH MY FREAKING--"
    "Something smashes."
    k "WHAT IN THE NAME OF--"
    "A shower of little noises like marbles over hardwood."
    k "WHAT EVEN IS THAT?"
    "A light finally pops on above you. You appear to be in an alien broom closet with like...alien cleaning supplies, you guess? One of the bottles just has CLEN written on it in permanent marker. You ask Karkat if he meant to transport the two of you into a closet."
    "A bucket rattles as he kicks it. He yelps and jumps backward onto your foot."
    k "WHAT THE HECK? MAKARA, WHAT IS WRONG WITH YOU."
    k "YOUR PERSONAL HABITS ARE ALMOST AS DISGUSTING AS YOUR PAN-ROTTING PURPLE WORDS, WHY IS YOUR FAYGO MIXED IN WITH YOUR SCRUB-POLES? DO YOU SOAK YOUR HUSKTOP IN IT? AND WHY DO YOU HAVE A BUCKET MIXED IN WITH YOUR CLEANING SUPPLIES?"
    k "DID YOU FIGURE NOBODY WOULD NOTICE?"
    k "SURPRISE, I NOTICED!"
    k "WHAT IN THE HELL--"
    "Karkat breaks off and after a moment you realize why. Heavy footsteps shuffle closer. Someone has heard the absolute rumpus tantrum that Karkat's kicking up."
    g "oH hEy HoLd Up My BrOtHeR"
    g "i'M hEaRiNg SoMeThInG iN tHe ScRuB cUbBy"
    g "sOmE sQuEaKbEaSt WhAt'S aLl GoT iTsElF tRaPpEd."
    "The door opens a crack. Karkat grabs your arm again."
    k "OH SHOOT."
    "A shadow looms on the wall, wild hair and tall horns."
    k "OH SHOOT."
    "Karkat squeezes your arm so hard it hurts."
    k "OH SHOOT OH SHOOT OH SHOOT OH SHOOT OH SHOOT."
    "The door opens a little wider, and you feel wetness on your arm where Karkat's claws have drawn blood. The door creaks, and you panic."
    "\[zap.\]"
    scene bg room with fade
    "You both crash down to the floor together in Karkat's respiteblock. Karkat's little horns jab you in the side."
    k "WHAT THE HECK WAS THAT FOR?"
    k "WHY DID YOU DO THAT?"
    "Because Karkat was freaking out and you were worried the two of you were in danger? And there was someone saying creepy stuff outside the closet door?"
    k "THAT IS A COMPLETE MISCHARACTERIZATION OF THE SCENARIO AND I'M TOTALLY DISGUSTED YOU'D EVEN BRING IT UP."
    "It's not a mischaracterization! He was totally losing it! Look, he was clinging on to you so hard he even drew blood!"
    "You show him your clawed up arm."
    "Karkat's reaction is immediate and overblown, which you are beginning to gather isn't out of character for him. He starts vigorously examining himself; he appears to be checking for injuries."
    "No, you insist, he's not the one bleeding. You are. He's so covered up in jeans and sweater that you have no idea how he'd even get cut in the first place."
    k "WAIT--THIS IS YOUR BLOOD?"
    "Um... yeah? What's the big deal? Besides the fact that he just scratched of you. You're willing to let it slide, though. This might just be the way he greets people? It's honestly kind of weird. Maybe you should just leave...?"
    k "WAIT, WHAT?"
    k "YOU CAN'T GO OUT THERE. IT ISN'T SAFE. NOT FOR PEOPLE LIKE..."
    "Karkat pulls himself warily to his feet. He's still looking at you like you're a bomb that might go off if he steps wrong. Slowly, he extends his own palm, and drags a claw across it. Crimson blood beads up and drips to the floor."
    k "IT ISN'T SAFE FOR PEOPLE LIKE US."
    "Clearly something is happening here, and it's probably a really deep and affecting moment, but you're just...not sure what you're supposed to do. You bleed, he bleeds, both of you bleed."
    "Ruining Karkat's possibly most impactful moment in the history of his life, his husktop beeps with an incoming message."
    "{i}TC started trolling CG{/i}"
    "{color=#880088}TC: hey KaRbRo{/color}"
    "{color=#880088}TC: i JuSt HaD tHiS wIcKeD dReAm That YoU wErE iN mY cLoSeT{/color}"
    "{color=#880088}TC: mIrAcLeS bRo :o){/color}"
    "{i}TC stopped trolling CG{/i}"
    "He stares at it incredulously for a moment before looking back to you."
    k "I AM JUST GOING TO PRETEND I'M NOT HOME TO ANSWER THAT."
    "Well, now that you have established that the two of you do indeed both have blood, Karkat appears to have warmed up to you a lot."
    "He even offers you something called \"grub juice\", which you're pretty sure is just coke? Except not as sweet. It's a little salty, actually. You take a few tiny polite sips and then pour it into a dead plant as soon as Karkat turns his back."
    "Now that you've recovered, your thoughts once again drift towards home. Sure, this place is nice, but you'll have to go back eventually. And right now, you aren't too confident in your abilities to do that."
    "I mean, you teleported to the Gamzee's closet just fine, but that wasn't quite where you were aiming. Maybe it would help if you had an idea of where your planet is. Or maybe you'd like to stay and recuperate a bit more."
    menu:
        ">Stay here":
            jump stay
        ">Ask Karkat for a map":
            jump ask

label ask:
    "Karkat is looking at you like you aren't making much sense, which is fair, because you really aren't making much sense."
    k "WELL, I GUESS YOU HAD TO GO SOMETIME."
    "He looks a little disappointed. The expression quickly fades, though."
    k "ALL RIGHT. LET'S DO THIS."
    "Karkat sits down at his desk and hits the space bar on his keyboard."
    k "WE COULD PROBABLY FIGURE OUT WHERE YOUR EARTH PLANET IS."
    k "WELL, NOT US SPECIFICALLY, UNLESS YOU'VE GOT SOME INCREDIBLY UNLIKELY AND WELL-HONED HUSKTOP SKILLS."
    "You've got no husktop skills, honed or otherwise."
    k "YEAH I'M NOT SURPRISED."
    k "HERE, JUST GIVE ME A SECOND. DON'T BREAK ANY OF MY STUFF."
    "You take a glance around the room, keeping your arms behind your back so as to make absolutely sure you don't break any of his stuff. His room is surprisingly tidy for someone as scattered as Karkat, mostly just weapons and movie posters."
    "It all has the air of someone who doesn't plan to live in a place for very long. It feels...temporary. Karkat is typing furiously with his mouth pulled into a little frown. That's his default, it appears. Every so often, though, he'll throw glances at the cuts on your arm. He really is hung up on your blood."
    "{color=#dddddd}CG: GOOD NEWS, CAPTOR. TONIGHT IS YOUR LUCKY NIGHT.{/color}"
    "{color=#dddddd}CG: FINALLY, YOU GET A CHANCE TO PUT YOUR MONEY WHERE YOUR DRIBBLING SNAGGLED-TOOTHED FLAP IS.{/color}"
    "{color=#dddddd}CG: I NEED YOU TO DO SOMETHING FOR ME.{/color}"
    "{color=#dddd00}TA: kk iif thii2 ii2 more whiiniing ii dont want to hear iit.{/color}"
    "{color=#dddd00}TA: and iif youre ju2t here two 2tart 2ome 2ort of 2lap fiight for wriiggler2 then you 2hould probably go two.{/color}"
    "{color=#dddd00}TA: becau2e iive got actual work ii need two do twoniight.{/color}"
    "{color=#dddddd}CG: HAHAHAHAHA OH MY GOSH. \"ACTUAL WORK\"? LIKE I EVEN BELIEVE THAT FOR A SECOND.{/color}"
    "{color=#dddddd}CG: YOU MEAN THE ACTUAL WORK OF MASHING BUTTONS ON YOUR HUSKTOP WHILE SOBBING INTO YOUR RECUPERACOON?{/color}"
    "{color=#dddd00}TA: ye2 hiilariou2 but can we 2kiip the garbage for ju2t one tiime iin our liive2.{/color}"
    "{color=#dddd00}TA: all that2 goiing two happen ii2 you 2ayiing 2omethiing you regret and then crytypiing over whether or not were 2tiil friiend2.{/color}"
    "{color=#dddddd}CG: OKAY FIRST OF ALL SCREW YOU.{/color}"
    "{color=#dddddd}CG: I DON'T HAVE TIME FOR ANY OF YOUR PATHETIC BURNS DUNKING ME INTO A CARTON OF WEAKSAUCE.{/color}"
    "{color=#dddddd}CG: THERE'S ACTUAL REAL, SERIOUS STUFF GOING DOWN.{/color}"
    "{color=#dddd00}TA: well now that weve wa2ted liike two miinute2 telliing each other how bu2y we are.{/color}"
    "{color=#dddd00}TA: what do you want.{/color}"
    "{color=#dddddd}CG: I NEED YOU TO CHECK SOMETHING IN THE IMPERIAL DATABASE FOR ME.{/color}"
    "{color=#dddddd}CG: AND I WANT YOU TO DO IT WITHOUT ASKING ME WHY I NEED IT.{/color}"
    "{color=#dddddd}CG: DEAL?{/color}"
    "{color=#dddd00}TA: waiit what the heck kk??{/color}"
    "{color=#dddd00}TA: ab2olutely no deal you diidnt even try two make a deal you ju2t told me two do 2omethiing iincrediibly iillegal and dangerou2!{/color}"
    "{color=#dddd00}TA: ii miight have a deathwii2h but iim not 2uiiciidal.{/color}"
    "{color=#dddd00}TA: 2o eiither tell me what crawled up your nook and laiid egg2 iin there or let me get back two work.{/color}"
    "{color=#dddddd}CG: OKAY. FINE. I'M ONLY TELLING YOU THIS BECAUSE WE'RE FRIENDS AND I TRUST YOU.{/color}"
    "{color=#dddddd}CG: THERE'S THIS...PERSON IN MY HIVE.{/color}"
    "{color=#dddd00}TA: per2on.{/color}"
    "{color=#dddddd}CG: YEAH. THEY AREN'T A TROLL. BUT THEY AREN'T A DRONE EITHER. I FIGURE THEY'RE AN ALIEN?{/color}"
    "{color=#dddddd}CG: BUT THEY SHOWED UP HERE WITH NO SPACESHIP AND HAVE NO IDEA WHERE THEIR PLANET IS.{/color}"
    "{color=#dddd00}TA: waiit they just 2howed up and have no iidea how they got here?{/color}"
    "{color=#dddd00}TA: 2orry kk iim tryiing to wrap my pan around thii2 but iim pretty 2ure youre me22iing wiith me.{/color}"
    "{color=#dddddd}CG: OH MY GOSH.{/color}"
    "{color=#dddddd}CG: COULD YOU JUST RUN THE SCAN?{/color}"
    "{color=#dddd00}TA: giive me a 2econd.{/color}"
    "{color=#dddd00}TA: okay there2 no planet wiith that name.{/color}"
    "{color=#dddd00}TA: 2o eiither your new aliien friiend2 world doe2ent exiist or iit ha2ent been found yet.{/color}"
    k "HEY, HE SAYS THAT--"
    k "OKAY WHAT THE HECK."
    "You step back from where you've been reading over Karkat's shoulder. You couldn't resist, he was just getting so mad, banging on the keyboard and making weird little growly noises."
    k "YOU THINK YOU CAN JUST LOOK INTO MY PRIVATE--"
    "Karkat goes absolutely silent. He's rigid; if he'd been a cat his hair would be standing straight up. You ask him what's wrong, and he shushes you so loudly you almost fall over from shock. You strain, and in the distance you think you hear a strange, staticky whirring."
    "Suddenly Karkat explodes into motion, grabbing your arm and pulling you out of his respiteblock and down the stairs."
    "In the living room, he tugs a thick black blanket from off the back of the couch and pulls up the rug in the center of the room. Beneath it is a trapdoor."
    "What the heck is--"
    k "BE QUIET."
    "His movements are quick and panicky, but also methodical. His jaw is set and his eyes are hard as he unbolts the trapdoor, gives it a hard yank to loosen it, and props it open."
    "Beneath it is a rectangular pit in the foundations of the house, the size and shape of a shallow grave. This isn't the first time he's done this. You doubt it's even the tenth."
    "So far Karkat has struck you as a little bit ridiculous. But now there's something fierce burning in him, something angry and distilled. The sound comes again, closer this time, and you see a hulking shadow out the window, huge and menacing and armored."
    "Karkat yanks you down into the pit with him, and wraps the two of you in the blanket. Then he closes the trapdoor and you are plunged into a darkness so absolute it's like you've stopped existing. What the hell is going on?"
    k "A DRONE."
    "Karkat's face is squished against your shoulder; the fear in his voice shudders you to your bones."
    k "IT'S JUST A ROUTINE CHECK. WE SHOULD BE FINE DOWN HERE"
    k "...MY...MY LUSUS DUG THIS."
    k "IT HIDES THE TEMPERATURE."
    "The temperature?"
    k "OF ME."
    k "OF US."
    k "OF OUR MUTATION."
    "You don't understand, but that doesn't stop you from being afraid. Impossibly heavy footsteps land on the floor above you. Karkat trembles. You have to do something."
    menu:
        ">Wait it out.":
            jump wait
        ">Teleport.":
            jump flee

label wait:
    k "WE'LL BE FINE."
    "Karkat mutters it to himself again and again."
    k "WE'LL BE FINE, WE'LL BE FINE."
    k "THIS ALWAYS WORKS, THERE'S NO REASON TO--"
    "A rusty, grating screech as the trapdoor is wrenched off its hinges. Light pours in. Two giant metal hands reach into the hole and pluck the both of you out. Karkat wriggles and bites like a cat trying to get free."
    "You don't have the chance--the drone tosses you bodily out of the way. Your head hits the wall, and everything goes a little strange and streaky after that."
    "When you come back to yourself, you're outside in the blazing morning heat with Karkat crouched over you. Did--did the two of you escape?"
    k "YEAH."
    "His voice is hollow. There is crimson blood smeared on his sweater and up to his chin, and you realize it must have come from the reopened cuts on your arm. Karkat must have carried you out of the hive."
    "The hive...."
    "Behind you, Karkat's house is in flames. The heat of the fire combines with the heat of the sun, until it feels like the two of you are standing on the edge of hell. Oh my gosh. Did the drone do that?"
    k "NO."
    k "MY LUSUS DID."
    k "I TOLD YOU, I HAVE EARLY WARNING SYSTEMS. HE GAVE ME A CHANCE TO GET OUT BEFORE TRIGGERING IT."
    "Is he...is he okay?"
    "Karkat gives you a look of utter disgust. He gestures toward the burning hive."
    k "I VERY MUCH DOUBT IT."
    "Okay. Okay. But the drone is dead, right? So he's safe."
    "Karkat releases a creaky wheezing sound that it takes you a second to realize is a laugh."
    k "GOSH, YOU REALLY ARE AN ALIEN. WHERE ARE YOU EVEN FROM? IT SOUNDS SO RELAXING."
    k "THAT ISN'T THE ONLY DRONE, YOU FREAK OF NATURE!"
    k "IT'S SEEN MY SIGN, IT'S HEARD MY VOICE! I'M ON RECORD AS CULL-ON-SIGHT! THERE IS ABSOLUTELY NOWHERE FOR ME TO GO!"
    "Shoot. Okay. Well, what about his friends? You really don't think Karkat is in any sort of state to make decisions, so you make an executive one for both of you. Also the sun is really hot out here, and your delicate skin is already starting to burn."
    "What had that friend's name been? Sollux?"
    "You take Karkat's hand, because the two of you are beyond holding each other under the armpits at this point."
    "\[zap.\]"
    "You appear in a residential street in a city, and for a second you think you must have traveled in time as well, since it's night again suddenly. But then you look up and see the strange purple/blue glimmer in the sky."
    "It's still day, but there's some sort of atmospheric shield between the killer sun and the city. You wonder why there isn't one over where Karkat lives. Maybe it's too rural."
    "Karkat yanks his hand out of yours. He is still holding the blanket he'd wrapped the two of you in, staring around in nervous little ticks. He looks even more scared than he had back in his bedroom. Clearly, he doesn't get out much."
    k "SHOOT."
    "A low chime rings out through the empty street. Karkat pulls his husktop out and looks at it like he can't remember what it is. Like everything normal has been wiped away and all that remains is horror."
    "{color=#dddd00}TA: kk what the heck??{/color}"
    "{color=#dddd00}TA: ii ju2t 2aw your name come up on the feed2.{/color}"
    "{color=#dddd00}TA: what diid you do you iidiiot?{/color}"
    "{color=#dddd00}TA: you cant ju2t 2tart 2howiing up on cull lii2t2!{/color}"
    "{color=#dddddd}CG: I DIDN'T DO ANYTHING.{/color}"
    "{color=#dddddd}CG: SOLLUX I{/color}"
    "{color=#dddddd}CG: THERE'S SOME STUFF ABOUT ME YOU DON'T KNOW.{/color}"
    "{color=#dddd00}TA: kk what the hell.{/color}"
    "{color=#dddddd}CG: OKAY, WELL, FIRST OF ALL I'M RIGHT OUTSIDE YOUR HIVESTEM.{/color}"
    "{color=#dddd00}TA: what.{/color}"
    "{color=#dddd00}TA: what are you talkiing about??{/color}"
    "{color=#dddd00}TA: ii2 thii2 the mutant 2tuff who care2 about that??{/color}"
    "{color=#dddd00}TA: tz know2 too 2he 2ay2 2he can ta2te our blood color2 through the 2creen whiich ii2 all kiind2 of freaky.{/color}"
    "{color=#dddddd}CG: HOW DOES THAT EVEN WORK?{/color}"
    "{color=#dddddd}CG: THE SCREENS AREN'T SCRATCH AND SNIFF! HOW THE--{/color}"
    "{color=#dddddd}CG: IT DOESN'T MATTER. WOW. I ACTUALLY DO NOT CARE ABOUT ANY OF TEREZI'S CACKLING RIGHT NOW.{/color}"
    "{color=#dddddd}CG: EVERYTHING IS RUINED FOREVER.{/color}"
    "As if in agreement, a familiar crackling whirr starts up somewhere close by. You and Karkat look at each other in almost-comedic distress."
    "{color=#dddddd}CG: I--I HAVE TO GO.{/color}"
    "{color=#dddd00}TA: ju2t come up here okay well fiigure thii2 out.{/color}"
    "{color=#dddddd}CG: NO. ABSOLUTELY NOT, OH MY GOSH?{/color}"
    "{color=#dddddd}CG: YOU UTTER IMBECILE, YOU THINK YOUR LITTLE PAN SPARKS COULD DO ANYTHING AGAINST A CULLING DRONE?{/color}"
    "{color=#dddddd}CG: I KNOW YOU HAVE A DEATHWISH, BUT I'M NOT GOING TO ASSIST YOU IN A HYSTERICAL SUICIDE.{/color}"
    "{color=#dddd00}TA: you dont know anythiing about me or my deathwii2h kk.{/color}"
    "{color=#dddd00}TA: come up2taiir2.{/color}"
    "Tears drip off his Karkat's jaw in blurry streaks of red."
    k "GET ME OUT OF HERE."
    k "AND DON'T YOU DARE ASK ME WHAT'S WRONG."
    "You don't, and he doesn't answer Sollux's message. You just get him out of there."
    "\[zap.\]"
    scene bg out with fade
    "You find yourself in the woods. The sun has just about set, and the trees only add to the darkness."
    "Karkat's eyes are dull, his hair a tangled mass of curls so thick they look like twisted wire."
    k "I FIGURED OUT WHY THE BLANKET DIDN'T WORK."
    "He shakes the blanket, which he's been holding on to all day, the last remnant of what is most likely by now just a smoking wreck."
    k "WITH TWO MUTANTS IN THERE, WE WERE TOO WARM."
    k "YEARS OF PERFECTING MY 'HIDING LIKE AN OINKBEAST FROM THE SLAUGHTER' TECHNIQUE, AND IT'S ALL DECIMATED BY SOME CLUELESS IDIOT IN A HOODIE."
    k "JUST KARKAT OUT HERE HAVING A NORMAL DAY!"
    k "THANK YOU, INEXORABLE MARCH OF FATE AND THE UNIVERSE!"
    k "I MEET SOMEONE WITH THE SAME DISGUSTING DEFORMITY AS ME, AND THEY IMMEDIATELY RUIN MY LIFE."
    k "THIS IS WHY I DON'T LET PEOPLE INTO MY HIVE!"
    "Karkat..."
    "There is so much hatred wrapped up in his voice, in his words, and you don't think it's hatred for you."
    "You ask him what you can do. You want to fix this."
    k "I THINK YOU'VE DONE ENOUGH."
    "Karkat bundles himself up in the blanket, even though it isn't cold. He turns away."
    "Darn it, you can't leave him like this! This is your one friend on the planet (well, this planet, anyway), and you can't watch him turn into a homeless hobo! You're fixing this, whether he likes it or not."
    "Karkat is still turned away. His husktop is unattended. You reach for it quietly."
    "\[Yoink!\]"
    "You have successfully yoinked the husktop."
    "Taking a moment to figure out the controls (luckily, the universe is feeling generous and the Hussie is feeling lazy, so it's just a retextured computer), you set up a memo to the eleven trolls on his chumroll."
    "{color=#dddddd}CG: Hey everyone, I'm homeless and in the woods! Heeeeelp!{/color}"
    "You wait for a few moments until someone replies."
    "{color=#aa0088}CA: wwhat do you expect me to do abowwt it{/color}"
    "{color=#aa0088}CA: ivve got things to do besides cater to landdwwelers{/color}"
    "{color=#aa0088}CA: specially ones wwho lovve me not{/color}"
    "Well, it's not quite the response you were expecting. But someone else is replying now."
    "{color=#008822}GA: Are You Okay? How Did This Happen?{/color}"
    "{color=#008822}GA: And What Happened To Your Typing Quirk?{/color}"
    "Quickly, you correct it to be more shouty."
    "{color=#dddddd}CG: A DRONE DESTROYED MY HOUSE AND KILLED OFF MY CRABDADDY. RIGHT NOW I'M HIDING IN THE FOREST. OH, AND I MET A REALLY COOL ALIEN WHO'S PROBABLY THE BEST ALIEN IN THE UNIVERSE.{/color}"
    "{color=#88ff00}AC: :33 > hey, it sounds like you're near my place!{/color}"
    "{color=#88ff00}AC: :33 > *ac wiggles her whiskers in happiness{/color}"
    "{color=#88ff00}AC: :33 > prepurr for a warm welcome!{/color}"
    "Karkat won't know what hit him. You think this may be a good thing."
    "{b}The end{/b}"
    return


label flee:
    "You're not great at trying new things under pressure. And lying in a shallow hole while a troll boy digs his nubby little horns into your ribs and a mechanical monster stomps around upstairs definitely counts as pressure."
    "But if that drone finds you, it's going to be a whole lot worse."
    "You grab your friend and go."
    "\[zap.\]"
    j "it was really cool of jade to have us all over yesterday."
    j "it felt like a birthday present, kind of. especially since all of my other presents got lost in the mail!"
    j "actually the only one that didn't get lost was a little monsters poster my dad got me."
    j "he gave it to me a week early, almost like he knew that something weird was going to happen to the rest of my gifts?"
    d "thats wack"
    d "oh hey"
    "Your friends Dave and John are propped up on the futon, gaming the way only bros can game. I.E. with several bags of chips and a mostly empty 2 liter bottle of Mountain Dew on the couch between them."
    j "oh hey!"
    "You wave hello and try to catch your breath. You're a little unbalanced from the brutal shift between being buried alive to a chill Texas day with just a couple guys being dudes. Wait, how did John even get here?"
    d "oh right yeah turns out jades dog can teleport"
    d "wild right who knew"
    j "and hey, i didn't know you could teleport too!"
    j "that's awesome! maybe i'll get powers as well!"
    j "hey, now that you can defy physics, can you zap me back to my place later? my dad doesn't like me to be out too late..."
    j "i don't think he'd call the cops on me, but i just want to be on the safe side."
    d "btw whos that"
    d "and is he like"
    d "okay"
    "Oh yeah. Karkat. He's currently curled up on the ground with the blanket still wrapped around him. He's breathing very heavily and sort of clutching at the carpet."
    "You lean down to make sure he's cool, while telling Dave and John that he's an alien from another planet. You figured you'd bring him here, since things got a little too hot back in alien land."
    d "oh"
    d "cool i guess"
    d "hey dude"
    j "wait."
    j "he's an alien?"
    j "like...a real alien?"
    d "yeah john come on look hes got little horns"
    j "yeah, i can see that, but...come on, aliens?"
    d "oh so this is where you draw the line"
    d "our friend living alone on an island with nothing but her magical dog and taxidermied grandpa who she stuffed herself"
    d "isnt where you draw it"
    d "finding out that our new friend can teleport isnt where you draw it"
    j "i guess you have a point."
    j "all of that stuff just feels so normal now!"
    d "so i guess in theory you could bring us to visit this alien planet"
    d "maybe"
    d "not that thats anything id actually want to do"
    d "youd never catch me in space"
    d "space aint the place"
    d "oh damn write that down"
    "You love a good Strider freestyle any day of the week, but this isn't Dave's route, so you return your focus back to--"
    "Oh shoot, where did he go?"
    d "oh yeah the little dude just scurried out the door"
    d "probably should have mentioned that"
    "Yikes. You just brought Karkat to Earth and you've already lost him. Some friend you are!"
    "\[zap.\]"
    "You zap down to the ground floor of the apartment building. Nothing. You zap to the stairwell and look up. Nothing. No little alien boy. Shoot."
    "Remembering to keep calm, you zap up to the roof."
    "\[zap.\]"
    "You find Karkat standing silhouetted against the turgid Texas sky, shimmers of heat haze making him look strangely artificial. He's shading his eyes and staring up at the sun. Hey dude! Don't do that, you're going to hurt yourself!"
    k "OH. WOW. THANK YOU SO MUCH FOR THE ADVICE. I'M WAY TOO STUPID TO KNOW NOT TO LOOK DIRECTLY INTO A BURNING BALL OF FIRE."
    k "THE PAIN IS INTENSE AND SEARING, BUT I'M JUST A DUMB ANIMAL!"
    k "BY THE WAY, THIS SUN IS PATHETIC."
    "Well, this is another planet and another sun."
    k "YES, THANK YOU!"
    "He drops his hand and turns back to you. There are still cobwebs in his hair from the crawlspace."
    k "IS THIS WHERE YOU'RE FROM?"
    "Well, sort of. You figured your mind was on the topic of friends so that's why you zapped to Dave's house and not your own."
    k "THIS ALL FEELS... I DON'T KNOW."
    k "WRONG?"
    k "OR JUST REALLY WEIRD."
    k "YOU ZAPPED IN AND DRAGGED ME OUT OF MY HIVE TO AN ALIEN PLANET WHERE THE SUN ISN'T HOT ENOUGH TO BURN."
    "Well, it is definitely hot enough to burn. It just takes a little longer."
    k "SHUT UP, I WASN'T FINISHED."
    k "BEFORE YOU SHOWED UP EVERYTHING MADE SENSE. ROTTEN, HORRIBLE SENSE, BUT STILL SENSE. AND NOW...I DON'T KNOW."
    k "I JUST FEEL... IT'S HARD TO DESCRIBE."
    k "FLATTENED OUT."
    d "yeah i feel you"
    "You and Karkat both jump. Dave has ninjaed up the stairs and leaned casually against the brick wall. Dang, how long has he been standing there? And where's John?"
    d "oh he just disappeared"
    "Wait what?"
    d "yeah its weird this swirling void wormhole just opened up in the tv and sucked him right in."
    "WHAT?"
    d "lol im joking with you"
    d "johns in the bathroom"
    d "but i had you for a second didnt i"
    "Oh yeah. Hilarious. He sure got you. Also, you're pretty sure the scene moved up here so you could talk to Karkat without Dave coming in and making all of this about him again."
    "Dave adjusts his shades."
    d "grey dude you ever play minecraft. its like, real life, but with more cubes"
    "{b}The end{/b}"
    return

label stay:
    k "FINE. YOU CAN STAY HERE. BUT ONLY UNTIL YOU GET YOURSELF SORTED OUT ENOUGH TO LEAVE."
    "All right! You're getting to stay with your buddy Karkat! It will be like a sleepover that never ends!"
    k "DID THE LAST THING I SAID NOT REGISTER AT ALL?"
    "He doesn't seem angry, though."
    "He sits down on his chair. After a moment, he realizes there's no chair for you and moves to the sofa where you can both sit."
    k "I DON'T USUALLY INVITE PEOPLE OVER. SORRY ABOUT IF IT'S, UH, A LITTLE MESSY."
    "You assure him that it's okay. Your room is way messier than this!"
    k "WHO WOULD'VE GUESSED."
    "You sit in silence for a few minutes."
    k "WELL, WE COULD SIT AND STARE LIKE THIS FOR THE REST OF THE DAY, OR I GUESS WE COULD WATCH A MOVIE."
    menu:
        "Watch movie":
            k "GREAT."
        "Sit and stare":
            "You stare at him for another minute. He stares back at you."
            k "THAT WAS A RHETORICAL QUESTION, YOU KNOW?"
    k "SO, WHAT MOVIE ARE WE GOING TO WATCH?"
    "You look through your options. He has an impressive collection, all of which are titled in Trollian. You suggest that he pick one, since you're not familiar with any of them."
    "He looks through the disks before picking one up."
    k "HOW ABOUT THIS ONE?"
    "You don't have the slightest clue what it's about. The cover features two trolls looking at one another soulfully, and two more looking on murderously."
    k "THIS IS {i}THE BALLAD OF A LOWBLOOD FEMALE AND A HIGHBLOOD MALE TROLL WHO ARE IN LOVE BUT THE FEMALE WAS IN A PREVIOUS RED RELATIONSHIP WITH A HIGHBLOOD FEMALE WHICH HAS NOW TURNED BLACK SO SHE WANTS TO RUIN HER LIFE{/i}"
    k "{i}AND THE MALE'S MORAIL THINKS THE HIGHBLOOD FEMALE WOULD BE A BETTER MATCH FOR HIM AND WANTS TO NUDGE HIM TOWARDS A MATESPRITESHIP WITH HER, WHILE STRUGGLING WITH HIS OWN ASHEN FEELINGS FOR THE LOWBLOOD FEMALE{/i}"
    "He takes a deep breath."
    k "DO YOUR THINK YOU'LL LIKE IT?"
    "Surprisingly, you do."
    "Now you have the urge to explain troll romance to all your friends."
    "{b}The end{/b}"
    return